import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "1.5rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      fontFamily: {
        sans: ['"Inter"', 'system-ui', 'sans-serif'],
        display: ['"Space Grotesk"', '"Inter"', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          glow: "hsl(var(--primary-glow))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        stat: {
          int: "hsl(var(--stat-int))",
          str: "hsl(var(--stat-str))",
          dis: "hsl(var(--stat-dis))",
          cha: "hsl(var(--stat-cha))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      backgroundImage: {
        "gradient-primary": "var(--gradient-primary)",
        "gradient-cyber": "var(--gradient-cyber)",
        "gradient-cool": "var(--gradient-cool)",
        "gradient-warm": "var(--gradient-warm)",
        "gradient-xp": "var(--gradient-xp)",
      },
      boxShadow: {
        "glow-primary": "var(--shadow-glow-primary)",
        "glow-secondary": "var(--shadow-glow-secondary)",
        "glow-accent": "var(--shadow-glow-accent)",
        "elegant": "var(--shadow-elegant)",
        "card-glass": "var(--shadow-card)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 4px)",
        sm: "calc(var(--radius) - 8px)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up":   { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "fade-in":   { "0%": { opacity: "0", transform: "translateY(8px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "scale-in":  { "0%": { opacity: "0", transform: "scale(0.96)" }, "100%": { opacity: "1", transform: "scale(1)" } },
        "slide-up":  { "0%": { opacity: "0", transform: "translateY(20px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "breathe":   { "0%,100%": { transform: "scale(1)", filter: "drop-shadow(0 0 30px hsl(var(--primary) / 0.45))" }, "50%": { transform: "scale(1.02)", filter: "drop-shadow(0 0 50px hsl(var(--primary) / 0.7))" } },
        "float":     { "0%,100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-6px)" } },
        "xp-shimmer": { "0%": { backgroundPosition: "0% 0%" }, "100%": { backgroundPosition: "200% 0%" } },
        "xp-pop":    { "0%": { opacity: "0", transform: "translateY(0) scale(0.8)" }, "30%": { opacity: "1", transform: "translateY(-12px) scale(1.05)" }, "100%": { opacity: "0", transform: "translateY(-60px) scale(1)" } },
        "level-up":  { "0%": { opacity: "0", transform: "scale(0.5)" }, "40%": { opacity: "1", transform: "scale(1.15)" }, "100%": { opacity: "0", transform: "scale(2.2)" } },
        "pulse-glow": { "0%,100%": { boxShadow: "0 0 0 0 hsl(var(--primary) / 0.4)" }, "50%": { boxShadow: "0 0 0 12px hsl(var(--primary) / 0)" } },
        "spin-slow": { from: { transform: "rotate(0)" }, to: { transform: "rotate(360deg)" } },
        "flame":     { "0%,100%": { transform: "scale(1) rotate(-2deg)", filter: "hue-rotate(0deg)" }, "50%": { transform: "scale(1.08) rotate(2deg)", filter: "hue-rotate(15deg)" } },
        "particle":  { "0%": { opacity: "0", transform: "translate(0,0)" }, "30%": { opacity: "1" }, "100%": { opacity: "0", transform: "translate(var(--tx,40px),var(--ty,-40px))" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up":   "accordion-up 0.2s ease-out",
        "fade-in":  "fade-in 0.4s ease-out both",
        "scale-in": "scale-in 0.3s cubic-bezier(0.34,1.56,0.64,1) both",
        "slide-up": "slide-up 0.4s ease-out both",
        "breathe":  "breathe 4s ease-in-out infinite",
        "float":    "float 4s ease-in-out infinite",
        "xp-shimmer": "xp-shimmer 3s linear infinite",
        "xp-pop":   "xp-pop 1.4s ease-out forwards",
        "level-up": "level-up 1.2s ease-out forwards",
        "pulse-glow": "pulse-glow 2s ease-out infinite",
        "spin-slow": "spin-slow 14s linear infinite",
        "flame":    "flame 1.4s ease-in-out infinite",
        "particle": "particle 1.6s ease-out forwards",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
